services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      # Move to app directory level
      - ../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # load-balancer:
  #   image: traefik
  migrations-runner:
    build:
      context: ../..
      dockerfile: docker/migrations-runner/Dockerfile
    env_file:
      - ../../.env
  app:
    # todo: replace with env variables?
    image: "ghcr.io/shazgames1/readwell-next-app:latest"
    depends_on:
      migrations-runner:
        condition: service_completed_successfully
    env_file:
      # Move to app directory level
      - ../../.env
    ports:
      # We don't need 80 and 443 ports. Use load balancer instead
      # - "80:80"
      # - "443:443"

      # TODO: replace 80 port when load balancer will be set up
      - "80:3000"
volumes:
  postgres_data:
