services:
  db:
    image: postgres
    # TODO: remove
    ports:
      - "5432:5432"
    env_file:
      # Move to app directory level
      - ../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  load-balancer:
    image: traefik
    command:
      - "--api.insecure=false"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ockunevanthony@yandex.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"

      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik/traefik.log"
    labels:
      traefik.enable: "true"
      # Setup traefik dashboard
      traefik.http.routers.mydashboard.rule: "Host(`traefik.read-well.ru`)"
      traefik.http.routers.mydashboard.entrypoints: "websecure"
      traefik.http.routers.mydashboard.tls.certresolver: "myresolver"
      traefik.http.routers.mydashboard.service: "api@internal"
      traefik.http.routers.mydashboard.middlewares: "myauth"
      traefik.http.middlewares.myauth.basicauth.users: "admin:{SHA}fZlA7E5ywpk+IAtzPGzKuR/Xgkg="
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/var/log/traefik
      - ./letsencrypt:/letsencrypt
    
  migrations-runner:
    build:
      context: ../..
      dockerfile: docker/migrations-runner/Dockerfile
    env_file:
      - ../../.env
  
  app:
    # todo: replace with env variables?
    image: "ghcr.io/shazgames1/readwell-next-app:latest"
    depends_on:
      migrations-runner:
        condition: service_completed_successfully
    env_file:
      # Move to app directory level
      - ../../.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextjs.rule: "Host(`read-well.ru`)"
      traefik.http.routers.nextjs.entrypoints: "websecure"
      traefik.http.routers.nextjs.tls.certresolver: "myresolver"
      traefik.http.services.nextjs.loadbalancer.server.port: 3000
volumes:
  postgres_data:

# TODO: add newtworks: internal (for services communication) and web (for external)
